### ISSUE TITLE
Support for implied decimals

### ISSUE THREAD

**Issue by VleoniAnovin** [org-tigris-jsapar/jsapar#9]
Hi

Is it possible to parse fixed-width content where numeric values are coded with `implied decimal` format?
I've checked here [https://org-tigris-jsapar.github.io/jsapar/basics_schema](url) but it seems that such feature is missing from the library.

About the implied decimal format: [https://www.ibm.com/support/knowledgecenter/en/SSLVMB_24.0.0/spss/base/syn_data_list_implied_decimal_positions.html](https://www.ibm.com/support/knowledgecenter/en/SSLVMB_24.0.0/spss/base/syn_data_list_implied_decimal_positions.html)

If not, are you welcoming pull requests from outside `org-tigris` organisation?

**Comment by stenix71** [comment]
Hi
At the moment there is no explicit support for implied decimal. You will get the integer value back from the parser and need to provide the integer value while parsing.
But it is a good idea to have built in support for it. I have faced the issue myself.
I am just about to release the 2.1 version of the library and maybe I could manage to sqeeze this in before the release. 

What would be your suggestion about how to specify this in the xml schema?
Something like this maybe with a new format type?
`<cell name="cost" ><implieddecimalformat decimals="2"/></cell>`
or like this to fit the current format but with a bit of cryptical pattern?
`<cell name="cost" ><format type="decimal" pattern"0<<2"/></cell>`
or any other suggestions?

You are more than welcome to participate with a pull request if you feel like doing some coding. Current working branch is 2.1-develop.

**Comment by stenix71** [comment]
I have implemented this for you. You can see this in action in 
https://github.com/org-tigris-jsapar/jsapar/blob/2.1-develop/examples/02_FixedWidthSchema.xml
An in the test
https://github.com/org-tigris-jsapar/jsapar/blob/2.1-develop/src/test/java/org/jsapar/JSaParExamplesTest.java#L98
It is deployed in the snapshot 2.1.0-SNAPSHOT but you can also clone the 2.1-develop branch and build it from there.
Have a go at it and let me know if this is meets your requirements or if you have any other idea.

**Comment by VleoniAnovin** [comment]
Hi @stenix71 

Sorry for the late response, I've had a few days off.
Regarding the proposed, improved and introduced description in xml schema - clean and perfect.

Just a few more questions:

- Are you going to include the new version here? [https://mvnrepository.com/artifact/org.tigris.jsapar/jsapar](url)

- Will the new version work under Java 8?

- Could you add some build instruction, when having a run with develop branch I had issues with failed tests and so on

Anyway, thanks for quick response and implementation, I'm going to include the new version in my project and let you know if something is wrong.

Cheers!

**Comment by stenix71** [comment]
Hi,
No problems. I was forced to make the release though because of another project. As for your questions:

1. It takes about 24 hours for a maven resource to propagate to all repositories once it is deployed to one of them. By now it should have reached them all.

1. Yes, it is built with Java 11 but with the new compiler option `-resouce 8` which states that the binaries should work for Java 8. Please file a bug report if it does not do so. I am also sadly still stuck in Java 8 in many of my projects.

1. I will do so. One reason could be that it requires Java 11 in order to build. It could also be an environment issue since I only build on Linux and in that case I would be interested to know what tests that are failing. Maybe it has to do with file paths or line separators?
